site_name: RoverLib Documentation
site_url: https://rover-project.github.io/Rover/
repo_url: https://github.com/Rover-Project/Rover
repo_name: Rover-Project/Rover

theme:
  name: material
  language: pt-BR
  logo: assets/logo-Rover.png
  palette: 
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs 
    - navigation.sections
    - navigation.expand
    - content.code.copy 
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight: 
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.tabbed: 
      alternate_style: true 
  - admonition 

plugins:
  - search