[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RoverLib"
version = "0.1.0"
description = "Uma biblioteca Python para manipulação de um Rover com Visão Computacional."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"

authors = [
  { name = "Sarmento", email = "sarmento.neto.francisco@gmail.com" },
  { name = "Gleidson", email = "gleidsonabstract.evgm@gmail.com" },
  { name = "Gutemberg", email = "gutoportelaa@gmail.com"},
  { name = "Hillan", email = "hillan1236@gmail.com"}
]

license = { file = "LICENSE" }

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: Robotics",
]

dependencies = [
  "numpy",
  "opencv-python",
  "click",
  "PyYAML"
  # picamera2
]

[project.optional-dependencies]
cli = ["click"]
dev = ["pytest", "black", "ruff"]

[project.scripts]
rover = "cli.main:cli"

[project.urls]
Homepage = "https://github.com/Rover-Project/Rover"
Repository = "https://github.com/Rover-Project/Rover"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."rover.camera"]
webcam = "plugins.camera.webcam:Webcam"
picamera2 = "plugins.camera.picamera2:PiCamera2"

[project.entry-points."rover.movement"]
l298n = "plugins.movement.gpio_l298n:L298NMotor"
mock = "plugins.movement.mock:MockMotor"