camera:
  fps: 30
  preview_resolution:
  - 640
  - 480
  resolution:
  - 3280
  - 2464
gpio:
  motor:
    right: [5, 6] # in3, in4
    left: [12, 13] # in1, in2
    calibration:
      right: 1
      left: 1