camera:
  fps: 30
  preview_resolution:
  - 640
  - 480
  resolution:
  - 3280
  - 2464
gpio:
  motor:
    right: [16, 25] # in3, in4
    left: [17, 26] # in1, in2
    calibration:
      right: 1
      left: 1