camera:
  fps: 30
  resolution:
    h: 4656
    w: 3496
  brigh: 0 # Brilho
  contrast: 1 # Contraste 
  saturation: 1 # Saturação

motor:
  right: [15, 16]
  left: [12, 11]
  calibration:
    left: 1
    right: 1