# Configuração para o script folowCircle
camera:
  fps: 30
  brigh: 0.5
  saturation: 1
  contrast: 1

gpio:
  motor:
    right: [16, 15] # in3, in4
    left: [11, 12] # in1, in2
    calibration:
      right: 0.6
      left: 1