# Configuração para o script folowCircle
camera:
  fps: 30
  brigh: 0.25
  saturation: 1
  contrast: 1

gpio:
  motor:
    right: [5, 6] # in3, in4
    left: [12, 13] # in1, in2
    calibration:
      right: 1
      left: 1